Avoid confusing "No module named 'mediagoblin'" error when _version.py missing
During development, if you run `bin/python3 -m pip install --editable .[test]`
without first creating a _version.py, you got a confusing error:

  ModuleNotFoundError: No module named 'mediagoblin'

This was caused when setuptools failed to look up the dynamic version
attribute. The setup.cfg file should instead refer to `mediagoblin.__version__`
and confine this indirection to mediagoblin/__init__.py. This makes the error a
much more helpful:

  AttributeError: module 'mediagoblin' has no attribute '__version__'